import "server-only";
import type { AccessDirectoryEntry } from "@/lib/access-directory-types";

// Esta lista é importada somente na rota administrativa /acessos.
// Ela não deve ser importada por componentes client-side.
export const accessDirectory: AccessDirectoryEntry[] = [
  { id: "clickup", name: "ClickUp", kind: "ferramenta", area: "Operação", owner: "Gestão", url: "https://app.clickup.com", access: "cofre", reviewedAt: "Agora", description: "Gestão de projetos e demandas.", username: "gestao@neveldigital.com.br", secret: "Nevel@gestao*157" },
  { id: "trello", name: "Trello", kind: "ferramenta", area: "Operação", owner: "Gestão", url: "https://trello.com", access: "cofre", reviewedAt: "Agora", description: "Quadros e acompanhamento de fluxos.", username: "gestao@neveldigital.com.br", secret: "Nevel@gestao*157" },
  { id: "notion", name: "Notion", kind: "ferramenta", area: "Processos", owner: "Gestão", url: "https://www.notion.so", access: "cofre", reviewedAt: "Agora", description: "Documentação e processos internos.", username: "gestao@neveldigital.com.br", secret: "Nevel@gestao*157" },
  { id: "slack-gestao", name: "Slack", kind: "ferramenta", area: "Comunicação", owner: "Gestão", url: "https://app.slack.com", access: "cofre", reviewedAt: "Agora", description: "Comunicação do time — gestão.", username: "gestao@neveldigital.com.br", secret: "Nevel@gestao*157" },
  { id: "discord", name: "Discord", kind: "ferramenta", area: "Comunicação", owner: "Gestão", url: "https://discord.com/app", access: "cofre", reviewedAt: "Agora", description: "Comunicação e comunidades.", username: "gestao@neveldigital.com.br", secret: "Nevel@gestao*157" },
  { id: "krea", name: "Krea", kind: "ia", area: "Criação", owner: "Gestão", url: "https://www.krea.ai", access: "cofre", reviewedAt: "Agora", description: "Exploração e geração visual com IA.", username: "gestao@neveldigital.com.br", secret: "Nevel@gestao*2026" },
  { id: "adobe", name: "Adobe", kind: "ferramenta", area: "Design", owner: "Time de criação", url: "https://creativecloud.adobe.com", access: "solicitar", reviewedAt: "—", description: "Aplicativos de criação da Adobe.", username: "", secret: "" },
  { id: "wasseller-gestao", name: "Wasseller", kind: "ferramenta", area: "Comercial", owner: "Gestão", url: "", access: "cofre", reviewedAt: "Agora", description: "Atendimento e automação no WhatsApp.", username: "gestao@neveldigital.com.br", secret: "Nevel@gestao*157" },
  { id: "wasseller-nevel", name: "Wasseller", kind: "ferramenta", area: "Comercial", owner: "Nevel Digital", url: "", access: "cofre", reviewedAt: "Agora", description: "Atendimento e automação no WhatsApp.", username: "neveldigital@gmail.com", secret: "Nevel@gestao*157" },
  { id: "asaas", name: "Asaas", kind: "ferramenta", area: "Financeiro", owner: "Financeiro", url: "https://www.asaas.com", access: "cofre", reviewedAt: "Agora", description: "Cobranças, pagamentos e gestão financeira.", username: "financeiro@neveldigital.com.br", secret: "Financeir0@Nev" },
  { id: "cloudflare", name: "Cloudflare", kind: "ferramenta", area: "Tecnologia", owner: "Gestão", url: "https://dash.cloudflare.com", access: "cofre", reviewedAt: "Agora", description: "DNS, domínios e proteção de sites.", username: "gestao@neveldigital.com.br", secret: "Nevel@gestao*157" },
  { id: "lovable", name: "Lovable", kind: "ia", area: "Tecnologia", owner: "Financeiro", url: "https://lovable.dev", access: "cofre", reviewedAt: "Agora", description: "Criação assistida de interfaces e aplicações.", username: "neveldigital@gmail.com", secret: "nevel@financeiro0" },
  { id: "respondi", name: "Respondi App", kind: "ferramenta", area: "Comercial", owner: "Nevel Digital", url: "", access: "cofre", reviewedAt: "Agora", description: "Atendimento e respostas automatizadas.", username: "neveldigital@gmail.com", secret: "Nevel@respondi0" },
  { id: "slack-riquer", name: "Slack", kind: "ferramenta", area: "Comunicação", owner: "Riquer", url: "https://app.slack.com", access: "aberto", reviewedAt: "Agora", description: "Comunicação do time — conta individual.", username: "riquerlmedina@gmail.com", secret: "" },
  { id: "calendly", name: "Calendly", kind: "ferramenta", area: "Comercial", owner: "Nevel Digital", url: "https://calendly.com", access: "cofre", reviewedAt: "Agora", description: "Agendamento de reuniões e atendimentos.", username: "neveldigital@gmail.com", secret: "Nevel@Calendly#" },
  { id: "comr", name: "COMR", kind: "ferramenta", area: "Operação", owner: "Gestão", url: "", access: "cofre", reviewedAt: "Agora", description: "Ferramenta operacional interna.", username: "gestao@neveldigital.com.br", secret: "Nevel@gestao*157" },
  { id: "supabase", name: "Supabase", kind: "ferramenta", area: "Tecnologia", owner: "Gestão", url: "https://supabase.com/dashboard", access: "cofre", reviewedAt: "Agora", description: "Banco de dados, autenticação e backend.", username: "gestao@neveldigital.com.br", secret: "Nevel@gestao*157" },
  { id: "cloudflare-novo", name: "Cloudflare novo", kind: "ferramenta", area: "Tecnologia", owner: "Nevel Digital", url: "https://dash.cloudflare.com", access: "cofre", reviewedAt: "Agora", description: "Nova conta para domínios e DNS.", username: "neveldigital@gmail.com", secret: "ACESSOCLOUD34!@" },
  { id: "vintepila", name: "VintePila", kind: "ferramenta", area: "Comercial", owner: "Nevel Digital", url: "", access: "cofre", reviewedAt: "Agora", description: "Marketplace e contratação de serviços.", username: "neveldigital@gmail.com", secret: "Vint@pilA@!" },
  { id: "gmail", name: "Gmail", kind: "ferramenta", area: "Comunicação", owner: "Nevel Digital", url: "https://mail.google.com", access: "cofre", reviewedAt: "Agora", description: "Caixa de e-mail institucional.", username: "neveldigital@gmail.com", secret: "nevel@rquesz10" },
  { id: "email-gestao", name: "E-mail gestão", kind: "ferramenta", area: "Comunicação", owner: "Gestão", url: "https://mail.google.com", access: "cofre", reviewedAt: "Agora", description: "Caixa de e-mail da gestão.", username: "gestao@neveldigital.com.br", secret: "nevel@gestao*" },
  { id: "email-financeiro", name: "E-mail financeiro", kind: "ferramenta", area: "Financeiro", owner: "Financeiro", url: "https://mail.google.com", access: "cofre", reviewedAt: "Agora", description: "Caixa de e-mail financeira.", username: "financeiro@neveldigital.com.br", secret: "nevel@financeiro*" },
  { id: "turbocloud", name: "TurboCloud", kind: "ferramenta", area: "Tecnologia", owner: "Nevel Digital", url: "", access: "cofre", reviewedAt: "Agora", description: "Hospedagem e serviços de infraestrutura.", username: "neveldigital@gmail.com", secret: "rquesz10" },
  { id: "instagram-nevel", name: "Instagram", kind: "ferramenta", area: "Mídia", owner: "Nevel Digital", url: "https://www.instagram.com", access: "cofre", reviewedAt: "Agora", description: "Perfil institucional Nevel Digital.", username: "Neveldigital_", secret: "Nevelmed157#@" },
  { id: "monday-core", name: "Monday", kind: "ferramenta", area: "Operação", owner: "Core Educação", url: "https://monday.com", access: "cofre", reviewedAt: "Agora", description: "Gestão de projetos da Core Educação.", username: "nevel@coreeducacao.com", secret: "nevel@gestao*157" },
  { id: "instagram-nevelmed", name: "Instagram", kind: "ferramenta", area: "Mídia", owner: "Nevelmed", url: "https://www.instagram.com", access: "cofre", reviewedAt: "Agora", description: "Perfil Nevelmed.", username: "nevelmed", secret: "Nevelmed157#@" },
  { id: "monday-nevelmed", name: "Monday", kind: "ferramenta", area: "Operação", owner: "Nevelmed", url: "https://monday.com", access: "cofre", reviewedAt: "Agora", description: "Gestão de projetos da Nevelmed.", username: "nevelmed@gmail.com", secret: "nevel@rquesz10" },
  { id: "figma-gestao", name: "Figma", kind: "ferramenta", area: "Design", owner: "Gestão", url: "https://www.figma.com/files", access: "cofre", reviewedAt: "Agora", description: "Arquivos e bibliotecas de design.", username: "gestao@neveldigital.com.br", secret: "Nevel@gestao*157" },
  { id: "briefing-think", name: "Briefing Think", kind: "ferramenta", area: "Processos", owner: "Think", url: "", access: "cofre", reviewedAt: "Agora", description: "Acesso à plataforma de briefing.", username: "briefing@thinkbrand.com.br", secret: "Briefing@think" },
  { id: "supabase-clinica", name: "Supabase", kind: "ferramenta", area: "Tecnologia", owner: "Gestão", url: "https://supabase.com/dashboard", access: "cofre", reviewedAt: "Agora", description: "Ambiente de dados Clínica System.", username: "gestao@neveldigital.com.br", secret: "Gestao@#ClinicaSytem0" },
  { id: "github", name: "GitHub", kind: "ferramenta", area: "Tecnologia", owner: "Gestão", url: "https://github.com", access: "cofre", reviewedAt: "Agora", description: "Repositórios e controle de versão.", username: "gestao@neveldigital.com.br", secret: "Gestao@#ClinicaSytem0" },
  { id: "vercel", name: "Vercel", kind: "ferramenta", area: "Tecnologia", owner: "Gestão", url: "https://vercel.com/dashboard", access: "cofre", reviewedAt: "Agora", description: "Deploy e hospedagem de aplicações.", username: "gestao@neveldigital.com.br", secret: "Gestao@#ClinicaSytem0" },
];
