import Link from "next/link";
import Script from "next/script";
import { ArrowUpRight, Bookmark, ExternalLink, LayoutPanelTop, Search, Sparkles } from "lucide-react";

const topics = ["Web design", "Thumbnails", "Direção de arte", "Poster", "Branding", "Texturas"];

export function ReferenceBank({ pinterestUrl }: { pinterestUrl: string }) {
  return <main className="min-h-0 flex-1 overflow-y-auto bg-[#f6f6f4] text-[#1e1e1c] scrollbar-clean">
    <header className="border-b border-[#e1e1dd] bg-white px-6 py-5 lg:px-8"><div className="mx-auto flex max-w-[1480px] flex-wrap items-end justify-between gap-4"><div><p className="text-[9px] font-semibold uppercase tracking-[.17em] text-[#85857f]">Operação · Repertório criativo</p><h1 className="mt-2 text-[25px] font-semibold tracking-[-.045em]">Banco de referências</h1><p className="mt-1 text-[11.5px] text-[#777772]">O mural vivo de inspirações da operação, conectado ao Pinterest interno.</p></div><a href={pinterestUrl} target="_blank" rel="noreferrer" className="inline-flex h-9 items-center gap-1.5 rounded-md bg-[#1e1e1c] px-3.5 text-[11px] font-medium text-white shadow-[0_1px_2px_rgba(0,0,0,.15)]">Abrir Pinterest interno <ExternalLink className="size-3.5" /></a></div></header>
    <div className="mx-auto max-w-[1480px] p-5 lg:p-7"><section className="grid gap-3 lg:grid-cols-[1.25fr_.75fr]"><div className="relative overflow-hidden rounded-xl bg-[#1e1e1c] p-6 text-white"><div className="relative z-10"><span className="inline-flex items-center gap-1.5 rounded-full border border-white/15 bg-white/10 px-2 py-1 text-[9px] font-medium"><Bookmark className="size-3" /> Pinterest interno</span><h2 className="mt-5 max-w-[480px] text-[29px] font-semibold leading-[1.03] tracking-[-.055em]">Referências para sair do óbvio, sem sair do contexto.</h2><p className="mt-3 max-w-[470px] text-[11px] leading-5 text-white/65">Navegue pelo quadro REF WEB para encontrar linguagens, composições e detalhes que aceleram o briefing criativo.</p><a href={pinterestUrl} target="_blank" rel="noreferrer" className="mt-5 inline-flex items-center gap-1 text-[10px] font-medium text-white">Ver mural completo <ArrowUpRight className="size-3" /></a></div><div className="pointer-events-none absolute -right-14 -top-10 size-52 rounded-full border-[30px] border-white/10" /><div className="pointer-events-none absolute bottom-[-90px] right-28 size-44 rotate-45 border border-white/15" /></div><div className="rounded-xl border border-[#dededb] bg-white p-5"><p className="text-[9px] font-semibold uppercase tracking-[.14em] text-[#898983]">Atalhos de pesquisa</p><div className="mt-4 grid grid-cols-2 gap-2">{topics.map((topic, index) => <a key={topic} href={`${pinterestUrl}?q=${encodeURIComponent(topic)}`} target="_blank" rel="noreferrer" className="group flex min-h-16 flex-col justify-between rounded-lg border border-[#e5e5e1] bg-[#fafaf8] p-3 transition-colors hover:border-[#aaa9a3] hover:bg-white"><span className="grid size-6 place-items-center rounded-md bg-[#eeeeeb] text-[9px] font-semibold text-[#444]">0{index + 1}</span><span className="mt-2 text-[10px] font-medium text-[#4b4b46]">{topic}<ArrowUpRight className="ml-1 inline size-2.5 opacity-0 transition-opacity group-hover:opacity-100" /></span></a>)}</div></div></section>
      <section className="mt-5 overflow-hidden rounded-xl border border-[#dededb] bg-white"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-[#e9e9e5] px-5 py-4"><div><h2 className="text-[12px] font-semibold">REF WEB</h2><p className="mt-1 text-[10px] text-[#85857f]">Mural sincronizado a partir do quadro do Pinterest</p></div><div className="flex items-center gap-2 text-[9.5px] text-[#777772]"><Sparkles className="size-3" /> Atualização no Pinterest</div></div><div className="grid min-h-[540px] place-items-center bg-[#fafaf8] p-4 sm:p-6"><div className="w-full overflow-hidden rounded-lg border border-[#e2e2de] bg-white p-3 sm:p-5"><div className="mb-4 flex items-center justify-between gap-3"><div className="flex items-center gap-2"><span className="grid size-7 place-items-center rounded-md bg-[#1e1e1c] text-[11px] font-semibold text-white">P</span><div><p className="text-[10.5px] font-semibold">Pinterest · REF WEB</p><p className="text-[8.5px] text-[#94948e]">Inspirações da operação</p></div></div><Link href={pinterestUrl} target="_blank" className="inline-flex items-center gap-1 text-[9.5px] font-medium text-[#555]">Abrir em tela cheia <ExternalLink className="size-3" /></Link></div><div className="relative min-h-[440px]"><a data-pin-do="embedBoard" data-pin-board-width="1100" data-pin-scale-height="440" data-pin-scale-width="100" href={pinterestUrl} className="absolute inset-0 z-10" aria-label="Abrir quadro REF WEB no Pinterest" /><div className="absolute inset-0 grid place-items-center text-center"><div><LayoutPanelTop className="mx-auto size-5 text-[#8a8a84]" /><p className="mt-3 text-[10px] font-medium text-[#555]">Carregando mural do Pinterest…</p><p className="mt-1 text-[9px] text-[#999]">Caso o mural não carregue, abra o quadro em uma nova aba.</p></div></div></div></div></div></section>
      <aside className="mt-4 flex gap-3 rounded-lg border border-[#dededb] bg-white p-4"><span className="grid size-7 shrink-0 place-items-center rounded-md bg-[#eeeeeb] text-[#555]"><Search className="size-3.5" /></span><div><h2 className="text-[10.5px] font-semibold">Como usar no briefing</h2><p className="mt-1 max-w-[820px] text-[10px] leading-4 text-[#75756f]">Abra uma referência, identifique composição, tipografia, ritmo e linguagem visual. Use o link do Pin no briefing para registrar a direção escolhida.</p></div></aside>
    </div><Script async strategy="afterInteractive" src="https://assets.pinterest.com/js/pinit.js" />
  </main>;
}
