"use client";

import * as React from "react";
import { Check, ChevronDown, CircleHelp, Copy, ExternalLink, Eye, EyeOff, Filter, KeyRound, LockKeyhole, Plus, Search, ShieldCheck } from "lucide-react";
import type { AccessDirectoryEntry, AccessKind, AccessState } from "@/lib/access-directory-types";

const accessLabels: Record<AccessState, string> = { cofre: "Protegido", aberto: "Aberto", solicitar: "Solicitar" };
const platformMarks: Record<string, string> = {
  ClickUp: "⌁", Trello: "▦", Notion: "N", Slack: "S", Discord: "D", Krea: "K", Adobe: "A", Wasseller: "W", Asaas: "a", Cloudflare: "CF", Lovable: "L", "Respondi App": "R", Calendly: "C", COMR: "C", Supabase: "S", VintePila: "V", Gmail: "M", "E-mail gestão": "@", "E-mail financeiro": "$", TurboCloud: "TC", Instagram: "◎", Monday: "m", Figma: "F", "Briefing Think": "BT", GitHub: "GH", Vercel: "▲",
};

export function AccessDirectory({ initialEntries }: { initialEntries: AccessDirectoryEntry[] }) {
  const [entries, setEntries] = React.useState(initialEntries);
  const [query, setQuery] = React.useState("");
  const [kind, setKind] = React.useState<"todos" | AccessKind>("todos");
  const [access, setAccess] = React.useState<"todos" | AccessState>("todos");
  const [isFormOpen, setFormOpen] = React.useState(false);
  const filtered = React.useMemo(() => entries.filter((entry) => {
    const term = query.trim().toLocaleLowerCase("pt-BR");
    return (!term || `${entry.name} ${entry.username} ${entry.area} ${entry.owner}`.toLocaleLowerCase("pt-BR").includes(term)) && (kind === "todos" || entry.kind === kind) && (access === "todos" || entry.access === access);
  }), [access, entries, kind, query]);

  return <main className="min-h-0 flex-1 overflow-y-auto bg-[#f7f7f6] scrollbar-clean">
    <header className="border-b border-[#e1e1de] bg-white px-6 py-5 lg:px-8"><div className="mx-auto flex max-w-[1480px] flex-wrap items-end justify-between gap-4"><div><p className="text-[9px] font-semibold uppercase tracking-[.17em] text-[#858580]">Admin & Gestão · Base interna</p><h1 className="mt-2 text-[25px] font-semibold tracking-[-.045em] text-[#20201e]">Planilha de acessos</h1><p className="mt-1 text-[11.5px] text-[#777772]">Ferramentas, contas e referências operacionais em um único lugar.</p></div><button type="button" onClick={() => setFormOpen(true)} className="inline-flex h-9 items-center gap-1.5 rounded-md bg-[#1e1e1c] px-3.5 text-[11px] font-medium text-white shadow-[0_1px_2px_rgba(0,0,0,.15)]"><Plus className="size-3.5" /> Adicionar acesso</button></div></header>
    <div className="mx-auto max-w-[1480px] p-5 lg:p-7">
      <section className="grid gap-3 sm:grid-cols-3"><Metric icon={KeyRound} label="Plataformas" value={entries.length} detail="Contas e ferramentas mapeadas" /><Metric icon={LockKeyhole} label="Com credenciais" value={entries.filter((entry) => entry.secret).length} detail="Senha copiada sem ficar exposta" /><Metric icon={ShieldCheck} label="Permissão" value="Admin + gestão" detail="Base restrita ao time autorizado" /></section>
      <section className="mt-5 overflow-hidden rounded-lg border border-[#dededb] bg-white shadow-[0_1px_2px_rgba(0,0,0,.025)]"><div className="flex flex-col gap-3 border-b border-[#e9e9e6] p-4 lg:flex-row lg:items-center lg:justify-between"><label className="relative w-full lg:max-w-[365px]"><Search className="pointer-events-none absolute left-3 top-1/2 size-3.5 -translate-y-1/2 text-[#92928c]" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar plataforma, login ou responsável" className="h-8 w-full rounded-md border border-[#dfdfdb] bg-[#fbfbfa] pl-8 pr-3 text-[10.5px] outline-none placeholder:text-[#a4a49e] focus:border-[#555550]" /></label><div className="flex flex-wrap gap-2"><FilterSelect label="Tipo" value={kind} onChange={(value) => setKind(value as "todos" | AccessKind)} options={[["todos", "Todos"], ["ferramenta", "Ferramentas"], ["referência", "Referências"], ["biblioteca", "Bibliotecas"], ["ia", "IA"]]} /><FilterSelect label="Estado" value={access} onChange={(value) => setAccess(value as "todos" | AccessState)} options={[["todos", "Todos"], ["cofre", "Protegidos"], ["aberto", "Abertos"], ["solicitar", "Solicitar"]]} /></div></div><div className="overflow-x-auto scrollbar-clean"><table className="min-w-[1040px] w-full text-left"><thead className="border-b border-[#e9e9e6] bg-[#f6f6f4] text-[8.5px] font-semibold uppercase tracking-[.13em] text-[#82827d]"><tr><th className="px-4 py-3">Plataforma</th><th className="px-3 py-3">Usuário / e-mail</th><th className="px-3 py-3">Senha</th><th className="px-3 py-3">Área</th><th className="px-3 py-3">Conta</th><th className="px-3 py-3">Estado</th><th className="px-4 py-3 text-right">Link</th></tr></thead><tbody className="divide-y divide-[#eeeeeb]">{filtered.map((entry) => <AccessRow key={entry.id} entry={entry} />)}{filtered.length === 0 && <tr><td colSpan={7} className="px-4 py-14 text-center"><CircleHelp className="mx-auto size-4 text-[#a5a59f]" /><p className="mt-2 text-[10.5px] text-[#85857f]">Nenhum item corresponde aos filtros atuais.</p></td></tr>}</tbody></table></div><div className="flex items-center justify-between gap-4 border-t border-[#e9e9e6] bg-[#fbfbfa] px-4 py-3"><p className="text-[9.5px] text-[#85857f]">Mostrando <b className="font-medium text-[#4c4c47]">{filtered.length}</b> de {entries.length} registros.</p><p className="inline-flex items-center gap-1.5 text-[9.5px] text-[#777772]"><LockKeyhole className="size-3" /> Senhas ficam mascaradas e podem ser copiadas.</p></div></section>
      <aside className="mt-4 flex gap-3 rounded-lg border border-[#dfdfdb] bg-white p-4 text-[#5f5f59]"><span className="grid size-7 shrink-0 place-items-center rounded-md bg-[#eeeeeb]"><ShieldCheck className="size-3.5" /></span><div><h2 className="text-[10.5px] font-semibold">Uso restrito</h2><p className="mt-1 max-w-[820px] text-[10px] leading-4">Essa página é visível somente para administradores e membros da Gestão. Revele uma senha apenas quando necessário e evite compartilhar a tela durante o acesso.</p></div></aside>
    </div>
    {isFormOpen && <CreateAccessDialog onClose={() => setFormOpen(false)} onCreate={(entry) => { setEntries((current) => [entry, ...current]); setFormOpen(false); }} />}
  </main>;
}

function Metric({ icon: Icon, label, value, detail }: { icon: React.ComponentType<{ className?: string }>; label: string; value: string | number; detail: string }) { return <section className="relative overflow-hidden rounded-lg border border-[#dededb] bg-white p-4 text-[#242422]"><Icon className="absolute right-4 top-4 size-4 opacity-30" /><p className="text-[9px] font-semibold uppercase tracking-[.13em] text-[#85857f]">{label}</p><p className="mt-3 text-[24px] font-semibold tracking-[-.055em] tabular">{value}</p><p className="mt-2 text-[9.5px] text-[#85857f]">{detail}</p></section>; }
function FilterSelect({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: [string, string][] }) { return <label className="relative inline-flex h-8 items-center gap-1.5 rounded-md border border-[#dfdfdb] bg-white px-2.5 text-[10px] text-[#686862]"><Filter className="size-3 text-[#999993]" /><span className="text-[#8a8a84]">{label}</span><select value={value} onChange={(event) => onChange(event.target.value)} className="appearance-none bg-transparent pr-3 text-[10px] font-medium text-[#464641] outline-none">{options.map(([optionValue, optionLabel]) => <option key={optionValue} value={optionValue}>{optionLabel}</option>)}</select><ChevronDown className="pointer-events-none absolute right-2 size-3 text-[#85857f]" /></label>; }
function ProductMark({ name }: { name: string }) { return <span className="grid size-7 shrink-0 place-items-center rounded-md border border-[#dbdbd7] bg-[#f3f3f1] text-[8px] font-semibold tracking-[-.06em] text-[#292927]">{platformMarks[name] ?? name.slice(0, 2).toUpperCase()}</span>; }
function AccessRow({ entry }: { entry: AccessDirectoryEntry }) { return <tr className="group transition-colors hover:bg-[#fafaf8]"><td className="px-4 py-3"><div className="flex items-center gap-2.5"><ProductMark name={entry.name} /><div><p className="text-[10.5px] font-semibold text-[#30302d]">{entry.name}</p><p className="mt-0.5 max-w-[210px] truncate text-[9px] text-[#8b8b85]">{entry.description}</p></div></div></td><td className="px-3 py-3"><CopyField value={entry.username} label="Copiar usuário" /></td><td className="px-3 py-3"><CopyField value={entry.secret} label="Copiar senha" secret /></td><td className="px-3 py-3"><span className="text-[9.5px] text-[#666660]">{entry.area}</span></td><td className="px-3 py-3"><span className="text-[9.5px] text-[#666660]">{entry.owner}</span></td><td className="px-3 py-3"><span className="inline-flex h-5 items-center rounded-full border border-[#ddddda] bg-[#f7f7f5] px-2 text-[8.5px] font-medium text-[#5f5f5a]">{accessLabels[entry.access]}</span></td><td className="px-4 py-3 text-right">{entry.url ? <a href={entry.url} target="_blank" rel="noreferrer" className="inline-flex h-7 items-center gap-1 rounded-md px-2 text-[9.5px] font-medium text-[#4e4e49] transition-colors hover:bg-[#ecece8] hover:text-[#1f1f1d]">Abrir <ExternalLink className="size-3" /></a> : <span className="text-[9px] text-[#a1a19b]">Sem link</span>}</td></tr>; }
function CopyField({ value, label, secret = false }: { value: string; label: string; secret?: boolean }) { const [revealed, setRevealed] = React.useState(false); const [copied, setCopied] = React.useState(false); async function copy() { if (!value) return; await navigator.clipboard.writeText(value); setCopied(true); window.setTimeout(() => setCopied(false), 1200); } if (!value) return <span className="text-[9px] text-[#aaa9a3]">—</span>; return <div className="flex max-w-[180px] items-center gap-1 rounded-md border border-[#e3e3df] bg-[#fbfbfa] py-1 pl-2 pr-1"><span className="min-w-0 flex-1 truncate font-mono text-[9px] text-[#393936]">{secret && !revealed ? "••••••••••" : value}</span>{secret && <button type="button" onClick={() => setRevealed((current) => !current)} className="grid size-5 place-items-center text-[#82827c] hover:text-[#222]"><span className="sr-only">{revealed ? "Ocultar" : "Mostrar"} senha</span>{revealed ? <EyeOff className="size-3" /> : <Eye className="size-3" />}</button>}<button type="button" onClick={() => void copy()} className="grid size-5 place-items-center text-[#82827c] hover:text-[#222]" aria-label={label}>{copied ? <Check className="size-3 text-[#222]" /> : <Copy className="size-3" />}</button></div>; }
function CreateAccessDialog({ onClose, onCreate }: { onClose: () => void; onCreate: (entry: AccessDirectoryEntry) => void }) { const [form, setForm] = React.useState({ name: "", username: "", secret: "", url: "", area: "", owner: "", kind: "ferramenta" as AccessKind, access: "cofre" as AccessState, description: "" }); const update = (field: keyof typeof form, value: string) => setForm((current) => ({ ...current, [field]: value })); return <div className="fixed inset-0 z-50 grid place-items-center bg-black/25 p-4 backdrop-blur-[1px]" role="dialog" aria-modal="true" onMouseDown={onClose}><form onMouseDown={(event) => event.stopPropagation()} onSubmit={(event) => { event.preventDefault(); if (!form.name.trim()) return; onCreate({ ...form, id: `${Date.now()}`, name: form.name.trim(), username: form.username.trim(), secret: form.secret.trim(), url: form.url.trim(), area: form.area.trim() || "Geral", owner: form.owner.trim() || "Não definido", description: form.description.trim() || "Ferramenta interna cadastrada.", reviewedAt: "Agora" }); }} className="w-full max-w-[475px] rounded-lg bg-white p-5 shadow-[0_18px_48px_rgba(0,0,0,.24)]"><p className="text-[9px] font-semibold uppercase tracking-[.15em] text-[#85857f]">Base interna</p><h2 className="mt-1 text-[19px] font-semibold tracking-[-.04em]">Adicionar acesso</h2><div className="mt-5 grid gap-3"><Input label="Plataforma" value={form.name} onChange={(value) => update("name", value)} placeholder="Ex.: Miro" required /><div className="grid grid-cols-2 gap-3"><Input label="Usuário / e-mail" value={form.username} onChange={(value) => update("username", value)} placeholder="Opcional" /><Input label="Senha" value={form.secret} onChange={(value) => update("secret", value)} placeholder="Opcional" /></div><Input label="Link de acesso" value={form.url} onChange={(value) => update("url", value)} placeholder="https://" type="url" /><div className="grid grid-cols-2 gap-3"><Input label="Área" value={form.area} onChange={(value) => update("area", value)} placeholder="Ex.: Design" /><Input label="Responsável" value={form.owner} onChange={(value) => update("owner", value)} placeholder="Ex.: Gestão" /></div></div><div className="mt-6 flex justify-end gap-2"><button type="button" onClick={onClose} className="h-8 rounded-md px-3 text-[10.5px] text-[#696963] hover:bg-[#f2f2ef]">Cancelar</button><button type="submit" className="inline-flex h-8 items-center gap-1.5 rounded-md bg-[#1e1e1c] px-3 text-[10.5px] font-medium text-white"><Plus className="size-3" /> Adicionar</button></div></form></div>; }
function Input({ label, value, onChange, placeholder, required, type = "text" }: { label: string; value: string; onChange: (value: string) => void; placeholder: string; required?: boolean; type?: string }) { return <label className="grid gap-1.5 text-[9.5px] font-medium text-[#64645e]">{label}<input value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} required={required} type={type} className="h-8 rounded-md border border-[#dfdfda] px-2.5 text-[10.5px] outline-none placeholder:text-[#aaa9a3] focus:border-[#5b5b56]" /></label>; }
